# Generated by Django 4.1.7 on 2023-05-05 12:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_tr', models.CharField(max_length=50, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='Language')),
                ('language_uz', models.CharField(max_length=100, null=True, verbose_name='Language')),
                ('language_en', models.CharField(max_length=100, null=True, verbose_name='Language')),
                ('language_ru', models.CharField(max_length=100, null=True, verbose_name='Language')),
                ('language_tr', models.CharField(max_length=100, null=True, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('context_uz', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('context_en', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('context_ru', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('context_tr', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_tr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='word', to='main.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='main.language')),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='main.short')),
            ],
        ),
    ]
