# Generated by Django 4.1.7 on 2023-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notword',
            name='text',
            field=models.TextField(),
        ),
    ]
